### ISSUE TITLE
Some questions about storing data.

### ISSUE THREAD

**Issue by tianmaliuixing** [PingjunChen/LiverCancerSeg#1]
Dear PingjunChen,
        Thank you very much for sharing your work. I'm also taking part in this competition, I look forward to communicating with you more.
        I have a question about storing dataa: I store my predictions in 'npy' or 'tif' format, which takes up a lot of storage space, about 2 gigabytes per image. Do you have good suggestions for storing pathological images？Here is my code to store the data.
       Thanks again for your sharing and looking forward to your Suggestions.
  
![image](https://user-images.githubusercontent.com/11666931/59241588-da4d4680-8c3a-11e9-9365-01a4e20838a0.png)

**Comment by PingjunChen** [comment]
@tianmaliuixing The slide image is saved in a pyramid manner, which means it has multiple levels. From my experience, it is not necessary to work on the 0th level image. One reason is the storage issue. Another reason is cropping patches from the 0th level of the slide with a size, e.g., 512*512, cannot cover enough context information for segmentation. For me, I usually work on the 1st level or 2nd level of the slide image. For the slides provided by this challenge, the width and height of the 2nd level slide image are 1/16 of the level-0 image, which can resolve the storage issue.  One loading example is in line 44-45 of [code](https://github.com/PingjunChen/LiverCancerSeg/blob/master/preprocess/check_mask.py). 

Another way to handle the storage issue is to generate patches on the fly. At least by using the openslide package, we can read patches through giving starting location, level, and size, as can be referred to [openslide docs](https://openslide.org/api/python/).
